# name:               '聆听<span style="padding: 0 4px; vertical-align: middle;">•</span>心动'
name:               'K<span style="padding: 0 4px 0 4px; ">•</span>Echo'
# title:              "聆听•心动"
title:              "K•Echo"
description:        "Listening to My Own Heart Beat "

avater:             "/images/avater.jpg"
url:                ""
author:             "Kean"
email:              "hikean@163.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            ""
github:             "hikean"
pinterest:          ""
linkedin:           ""
facebook:           ""

disqus_shortname:   ""

background:         "/images/background.jpg"

paginate:           8
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:title/

markdown:           kramdown
kramdown:
  input: GFM

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Blog"
    href:           "/blog"

sass:
  style:            compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
